main : main.c  ./mqv/2_step/*.c ./rabbit/*.c ./gost3411-2012/*.c
	gcc main.c ./mqv/2_step/gen_number.c ./mqv/2_step/get_data.c ./rabbit/rabbit.c ./gost3411-2012/gost3411-2012-core.c -o main -lgmp
run:
	./main
